project_id = "niqjltsnxqmsvgataryy"

[functions.marvia-chat]
verify_jwt = false

[functions.marvia-image]
verify_jwt = false

[functions.marvia-search]
verify_jwt = false

[functions.firecrawl-search]
verify_jwt = false